import Head from 'next/head'
import { Box, Flex, Heading, SimpleGrid, Text } from '@chakra-ui/react';
import { Inter } from 'next/font/google'
import SideBar from '@/components/SideBar';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>RoCall</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/RoCall_Icon.png" />
      </Head>
      <main>
        <Flex >
          {/* Side Bar */}
          <SideBar />

          {/* Content Area */}
          <Box ml="250px" p={10} flex="1">
            <Box margin={10}>
              <Text
                bgGradient='linear(to-l, #7928CA, #FF0080)'
                bgClip='text'
                fontSize='6xl'
                fontWeight='extrabold'
                marginBottom={10}
              >
                Project Based Learning
              </Text>
              {/*<Heading fontSize='30px' marginBottom={5}>Member : 青野, 朝倉, 秋山, 石井, 市毛</Heading>
              <Heading fontSize='30px'>Product : 自動出席確認装置</Heading>*/}
            </Box>

          </Box>
        </Flex>
      </main>
    </>
  )
}
